kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: nginx-app
  namespace: argocd

spec: 
  project: frontend-team
  source:
    repoURL: https://github.com/gajanan43/argocd-demos.git
    targetRevision: main
    path: ui_approach/nginx 
  destination:
    server: https://kubernetes.default.svc 
    namespace: frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true