kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: nginx-dev
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/gajanan43/argocd-demos.git
    targetRevision: main
    path: ui_approach/nginx 
  destination:  
    server: https://kubernetes.default.svc # Only difference is here in multicluster setup
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  